apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: job-service-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: job-service
  endpoints:
    - port: http
      path: /metrics
      interval: 5s