apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-service-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: worker-service
  endpoints:
    - port: http
      path: /metrics
      interval: 5s